# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "027d6da1114e6831f1e363f38af05c34"
name = "iyc-catalog-connector\r"
application_url = "https://localhost:8787"
embedded = false
handle = "rocket-pocket-iyc-catalog-connector"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://localhost:8787/auth/callback" ]

[pos]
embedded = false
